### ISSUE TITLE
Ferzoco_Braden_Presentation

### ISSUE THREAD

**Issue by wcolegrove** [BetaNYC/NYC-CIF#1]
[Civic Fellows Ferzoco Braden 102715.pptx](https://github.com/BetaNYC/NYC-CIF/files/25608/Civic.Fellows.Ferzoco.Braden.102715.pptx)

**Comment by noneck** [comment]
I've uploaded this to the https://github.com/BetaNYC/NYC-CIF/tree/master/Misc folder.
